salao/cadastros/cliente/urls.py
from django.urls import path
from . import views


app_name ='cadastros'
urlpatterns =[
    path(
        'cliente/',
        views.cadastro_usuario,
        name='cliente'
          ),
          
    path(
        'criar_cliente/', 
        views.criar_cliente, 
        name='criar_cliente'
        )
]

salao/core/urls.py
#criar uma side bar

from django.urls import path, include
from . import views


app_name ='core'
urlpatterns =[
    path(
        'home/'
        , views.sidebar, 
        name='home'
        ),
    #path('cadastro_gestor_cliente/', views.cadastro_gestor_cliente, name='cadastro_gestor_cliente')
]

salao/login/clientes/urls.py
from django.urls import path, include
from . import views


app_name ='login_cliente'
urlpatterns =[
    path('clientes/', views.login_user, name='clientes'),
]

salao/relatorios/urls.py
from django.urls import path, include
from .clientes import views as cliente_views
from .agendamentos import views as agend_views
from .geral import views as geral_views

app_name ='relatorios'
urlpatterns =[
    path(
        'clientes/', 
        cliente_views.relatorio_clientes, 
        name='relatorio_clientes'
        ),

    path(
        'agendamentos/',
        agend_views.relatorio_agendamentos,
        name='relatorio_agendamentos'
        ),

    path(
        'ver_cliente/<int:id>',
        cliente_views.ver_cliente,
        name='ver_cliente'
        ),

    path(
        'ver_agendamento/<int:id>',
        agend_views.ver_agendamento,
        name='ver_agendamento'
        ),
    
    path(
        'deletar_cliente/<int:id>',
        cliente_views.deletar_cliente,
        name='deletar_cliente'
        ),
    
    path(
        'deletar_agendamento/<int:id>',
        agend_views.deletar_agendamento,
        name='deletar_agendamento'
        ),

    path(
        'editar_agendamento/<int:id>',
        agend_views.editar_agendamento,
        name='editar_agendamento'
        ),

   
    path(
        'relatorio_geral/',
        geral_views.relatorio_geral,
        name='relatorio_geral'
        ),

    path(
        'imprimir/',
        agend_views.imprimir_relatorio_pdf,
        name='imprimir_relatorio'
        ),

    path('imprimir_layout/', 
         agend_views.imprimir_layout, 
         name='imprimir_layout'
         ),
]

salao/salao/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicos/', include('servicos.urls')),
    path('config/', include('configuracao.urls')),
    path('relatorios/',include('relatorios.urls')),
    path('cadastros/', include('cadastros.urls')),
    path('login/', include('login.urls')),
    path('home/', include('core.urls')),
    path('', include('home.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salao/cadastros/cliente/models.py
from django.db import models

from core.models import Base
# Create your models here.

#2.1.1 - Eu como recepcionista, quero cadastrar :
#clientes - nome, telefone, email, data de nascimento, cpf
#serviços - nome, descrição, preço
#profissionais - nome, telefone, email, especialidade


class Cliente(Base):
    nome = models.CharField(
        max_length=100, 
        verbose_name='Nome'
    )
    telefone = models.CharField(
        max_length=20, 
        verbose_name='Telefone'
        )
    email = models.EmailField(
        max_length=100, 
        verbose_name='Email'
        )
    cpf = models.CharField(
        max_length=11, 
        verbose_name='CPF', 
        unique=True
        )
    foto = models.ImageField(
        upload_to='clientes/', 
        blank=True, 
        null=True
    )
    
    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        db_table = 'cliente_cliente'
    
    def __str__(self):
        return f'{self.nome} - {self.cpf} - {self.data_nascimento} - {self.foto}'

salao/cliente/models.py
from django.db import models

from core.models import Base
# Create your models here.

#2.1.1 - Eu como recepcionista, quero cadastrar :
#clientes - nome, telefone, email, data de nascimento, cpf
#serviços - nome, descrição, preço
#profissionais - nome, telefone, email, especialidade


class Cliente(Base):
    nome = models.CharField(
        max_length=100, 
        verbose_name='Nome')
    telefone = models.CharField(
        max_length=20, 
        verbose_name='Telefone')
    email = models.EmailField(
        max_length=100, 
        verbose_name='Email')
    data_nascimento = models.DateField(
        verbose_name='Data de Nascimento')
    cpf = models.CharField(
        max_length=11, 
        verbose_name='CPF', 
        unique=True)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
    
    def __str__(self):
        return f'{self.nome} - {self.email} - {self.data_nascimento} - {self.cpf}'


class Servico(Base):
    nome = models.CharField(
        max_length=100, 
        verbose_name='Serviço'
        )
    descricao = models.TextField(
        verbose_name='Descrição'
        )
    preco = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        verbose_name='Valor'
        )

    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'
    
    def __str__(self):
        return f'{self.nome}'


class Profissional(Base):
    nome = models.CharField(
        max_length=100, 
        verbose_name='Nome'
        )
    telefone = models.CharField(
        max_length=20, 
        verbose_name='Telefone'
        )
    email = models.EmailField(
        max_length=100, 
        verbose_name='Email'
        )
    especialidade = models.ForeignKey(
        Servico,
        to_field='id',
        on_delete=models.CASCADE,
        verbose_name="especialidade"
        )
    data_contratacao = models.DateField(
        verbose_name='Data de Contratação'
        )

    class Meta:
        verbose_name = 'Profissional'
        verbose_name_plural = 'Profissionais'

    def __str__(self):
        return f'{self.nome} - Especialidade: {self.especialidade} - Contato: {self.telefone} - Email: {self.email}'

salao/cadastros/cliente/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Cliente
from relatorios.clientes.views import get_relatorio_clientes

# Create your views here.
def cadastro_usuario(request):
    if request.method == "GET":
        return render (request, "cadastros/clientes/cadastrar_login.html")
    else:
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        telefone = request.POST.get('telefone')
        cpf = request.POST.get('cpf')

        user = Cliente(
            nome=nome,
            email=email,
            telefone=telefone,
            cpf=cpf)
        
        user.save()

        return redirect('/cadastros/cliente/criar_cliente/')

def criar_cliente(request):
    # Inicia a consulta de clientes
    clientes = Cliente.objects.all()

    # Captura filtros do GET
    nome_filtrar = request.GET.get('nome_filtrar')
    email_filtrar = request.GET.get('email_filtrar')
    cpf_filtrar = request.GET.get('cpf_filtrar')

    # Aplica filtros
    if nome_filtrar:
        clientes = clientes.filter(nome__icontains=nome_filtrar)
    if email_filtrar:
        clientes = clientes.filter(email__icontains=email_filtrar)
    if cpf_filtrar:
        clientes = clientes.filter(cpf__icontains=cpf_filtrar)


    # Prepara o contexto com os dados filtrados e a quantidade de agendamentos
    consulta_cliente = get_relatorio_clientes(request)
    if request.method == "GET":
        contexto = {
            'clientes': consulta_cliente['clientes'],
            'qntd_clientes': consulta_cliente['qntd_clientes'],
            'pagina': consulta_cliente['pagina'],
            'limit': consulta_cliente['limit'],
        }
        return render(request, "cadastros/clientes/criar_cliente.html", contexto)

salao/login/clientes/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


# Create your views here.
def login_user(request):
    
    if request.method == "GET":
        return render (request, 'login.html')
    else:
        username=request.POST.get('username')
        senha=request.POST.get('senha')

        user = authenticate(username=username, password=senha)

        if user:
            login(request, user)

            return HttpResponse('Deu bom')
        else: 
            return HttpResponse('Usuario ou senha invalidos')

salao/relatorios/clientes/views.py
from math import ceil

from django.shortcuts import render, redirect

from servicos.agendamento.models import Agendamento
from cadastros.cliente.models import Cliente


def relatorio_clientes(request):
    limit = 25
    pagina = int(request.GET.get('pagina', 1))

    clientes = Cliente.objects.all()
    qntd_clientes = clientes.count()
    nome_filtrar=request.GET.get('nome_filtrar')
    email_filtrar=request.GET.get('email_filtrar')
    tipo_usuario_filtrar= request.GET.get('tipo_usuario_filtrar')

    if nome_filtrar:
        clientes = clientes.filter(nome__contains=nome_filtrar)
    
    if email_filtrar:
        clientes = clientes.filter(email__contains=email_filtrar)
    
    if tipo_usuario_filtrar:
        clientes = clientes.filter(tipo_usuario__iexact=tipo_usuario_filtrar.lower())

    total_paginas = ceil(qntd_clientes / limit)
    paginas = list(range(1, total_paginas + 1))

    offset = (pagina - 1) * limit
    clientes = clientes.order_by('nome')[offset:offset + limit]

    contexto = {
        'clientes': clientes,
        'qntd_clientes': qntd_clientes,
        'pagina': pagina,
        'limit': limit,
        'total_paginas': total_paginas,
        'paginas': paginas,
    }

    return render(
        request,
        "clientes/relatorio_clientes.html",
        contexto
        )


def ver_cliente(request,id):
    cliente=Cliente.objects.get(id=id)
    return  render(
        request,
        "clientes/ver_clientes.html",
        {'cliente': cliente}
        )


def ver_agendamento(request, id):
    agendamento=Agendamento.objects.get(id=id)
    return  render(
        request,
        "agendamentos/ver_agendamento.html",
        {'agendamento': agendamento}
    )


def deletar_cliente(request,id):
    cliente=Cliente.objects.get(id=id)
    cliente.delete()
    return redirect(
        '/cadastros/cliente/criar_cliente/'
        )

def deletar_agendamento(request, id):
    agendamento = Agendamento.objects.get(id=id)
    agendamento.delete()
    return redirect(
        '/relatorios/agendamentos/'
        )


def get_relatorio_clientes(request):
    limit = 10
    pagina = int(request.GET.get('pagina', 1))
    letra = request.GET.get("letra")  

    clientes = Cliente.objects.all()
    nome_filtrar=request.GET.get('nome_filtrar')
    email_filtrar=request.GET.get('email_filtrar')
    cpf_filtrar = request.GET.get('cpf_filtrar')
    phone_filtrar = request.GET.get('phone_filtrar')

    clientes = Cliente.objects.all()

    if nome_filtrar:
        clientes = clientes.filter(nome__contains=nome_filtrar)
    
    if email_filtrar:
        clientes = clientes.filter(email__contains=email_filtrar)

    if cpf_filtrar:
        clientes = clientes.filter(cpf__contains=cpf_filtrar)
    
    if phone_filtrar:
        clientes = clientes.filter(telefone__contains=phone_filtrar)
    
    if letra:
        clientes = Cliente.objects.filter(nome__istartswith=letra)
    

    qntd_clientes = clientes.count()

    total_paginas = ceil(qntd_clientes / limit)
    paginas = list(range(1, total_paginas + 1))

    offset = (pagina - 1) * limit
    clientes = clientes.order_by('nome')[offset:offset + limit]

    contexto = {
        'clientes': clientes,
        'qntd_clientes': qntd_clientes,
        'pagina': pagina,
        'limit': limit,
        'total_paginas': total_paginas,
        'paginas': paginas,
        'letra': letra
    }

    return (contexto)

salao/relatorios/clientes/templates/clientes/relatorio_clientes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Relatório de Clientes</title>  
    <link rel="stylesheet" href="{% static 'geral/css/geral_Style.css' %}">
</head>
<body>
    {% include 'core/navbar.html' %}
    {% include 'core/sidebar.html' %}
    <div class="header">
        <h1>Relatório Clientes</h1>
        <form class="filters" method="GET">
            {% csrf_token %}
            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome-filtrar" class="nome-filtrar">
            <label for="email">Email</label>
            <input type="text" id="email" name="email-filtrar" class="email-filtrar">
            <input type="submit" value="Filtrar" class="btn btn-success">
        </form>
    </div>
        <div class="grid">
      <div class="table-card">
        <h4><span class="qtd_age">Total de de clientes: {{ qntd_clientes }}</span></h4>
        
        <div class="paginacao">
        <span class="qtd_age">Paginas : </span>
        {% for page_num in paginas %}
          <a href="?pagina={{ page_num }}" class="page-number {% if page_num == pagina %}active{% endif %}">
          {{ page_num }}
          </a>
          {% endfor %}
        </div>

        <table>
          <thead>
            <tr>
              <th>CPF</th>
              <th>Nome</th>
              <th>Email</th>
              <th>Telefone</th>
              <th>Ativo</th>
            </tr>
          </thead>
          <tbody>
            {% for i in clientes %}     
            <tr>
                <td>{{ i.cpf}}</td>
                <td>{{ i.nome }}</td>
                <td>{{ i.email }}</td>
                <td>{{ i.telefone }}</td>
                <td>{{ i.ativo|yesno:"Sim,Não" }}</td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="5">Nenhum agendamento encontrado.</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
          <form>
          <span class="qtd_age">Total de de clientes: {{ qntd_clientes }}</span><br> <br>

          <div class="paginacao">
          {% if pagina > 1 %}
              <a class="form-btn" href="?pagina={{ pagina|add:-1 }}">Anterior</a>
          {%else%}
              <a class="form-btn" >Anterior</a>
          {% endif %}
          
          {% for page_num in paginas %}
          <a href="?pagina={{ page_num }}" class="page-number">
              {{ page_num }}
          </a>
          {% endfor %}

          {% if pagina < total_paginas %}
              <a class="form-btn" href="?pagina={{ pagina|add:1 }}">Próxima</a>
          {%else%}
              <a class="form-btn">Próxima</a>
          {% endif %}
          </div>
          </form> 
      </div>
      
</body>
</html>

salao/relatorios/clientes/templates/clientes/ver_clientes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Consulta de Clientes</title>
  <link rel="stylesheet" href="{% static 'agendamentos/css/relatorios_Style.css' %}">
</head>
<body>
  {% include 'core/navbar.html' %}
  {% include 'core/sidebar.html' %}
  <main class="container">
    <form class="div-log">
      <h5>Nome do Cliente: <span>{{ cliente.nome }}</span></h5>
      <h5>Email: <span>{{ cliente.email }}</span></h5>
      <h5>Telefone: <span>{{ cliente.telefone }}</span></h5>
      <h5>CPF: <span>{{ cliente.cpf }}</span></h5>
      <h5>Ativo: <span>{{ cliente.ativo|yesno:"Sim,Não" }}</span></h5>
    </form>
    <form class="">
      <a href="{% url 'relatorios:deletar_cliente' cliente.id %}" class="btn btn-danger acoes">Excluir</a>
      <a href="/relatorios/clientes/" class="btn btn-primary acoes">Voltar</a>
    </form>
  </main>

</body>
</html>