salao/cadastros/cliente/urls.py
from django.urls import path
from . import views


app_name ='cadastros'
urlpatterns =[
    path(
        'cliente/',
        views.cadastro_usuario,
        name='cliente'
          ),
          
    path(
        'criar_cliente/', 
        views.criar_cliente, 
        name='criar_cliente'
        )
]

salao/cadastros/urls.py
from django.urls import path, include

urlpatterns =[
   path(
       'cliente/', 
       include('cadastros.cliente.urls'),
        ),

   path(
       'funcionarios/', 
        include('cadastros.funcionarios.urls'),
        ),
        
   path(
       'servicos/', 
       include('cadastros.servicos.urls'),
       ),
]

salao/core/urls.py
#criar uma side bar

from django.urls import path, include
from . import views


app_name ='core'
urlpatterns =[
    path(
        'home/'
        , views.sidebar, 
        name='home'
        ),
    #path('cadastro_gestor_cliente/', views.cadastro_gestor_cliente, name='cadastro_gestor_cliente')
]

salao/login/clientes/urls.py
from django.urls import path, include
from . import views


app_name ='login_cliente'
urlpatterns =[
    path('clientes/', views.login_user, name='clientes'),
]

salao/relatorios/urls.py
from django.urls import path, include
from .clientes import views as cliente_views
from .agendamentos import views as agend_views
from .geral import views as geral_views

app_name ='relatorios'
urlpatterns =[
    path(
        'clientes/', 
        cliente_views.relatorio_clientes, 
        name='relatorio_clientes'
        ),

    path(
        'agendamentos/',
        agend_views.relatorio_agendamentos,
        name='relatorio_agendamentos'
        ),

    path(
        'ver_cliente/<int:id>',
        cliente_views.ver_cliente,
        name='ver_cliente'
        ),

    path(
        'ver_agendamento/<int:id>',
        agend_views.ver_agendamento,
        name='ver_agendamento'
        ),
    
    path(
        'deletar_cliente/<int:id>',
        cliente_views.deletar_cliente,
        name='deletar_cliente'
        ),
    
    path(
        'deletar_agendamento/<int:id>',
        agend_views.deletar_agendamento,
        name='deletar_agendamento'
        ),

    path(
        'editar_agendamento/<int:id>',
        agend_views.editar_agendamento,
        name='editar_agendamento'
        ),

   
    path(
        'relatorio_geral/',
        geral_views.relatorio_geral,
        name='relatorio_geral'
        ),

    path(
        'imprimir/',
        agend_views.imprimir_relatorio_pdf,
        name='imprimir_relatorio'
        ),

    path('imprimir_layout/', 
         agend_views.imprimir_layout, 
         name='imprimir_layout'
         ),
]

salao/salao/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicos/', include('servicos.urls')),
    path('config/', include('configuracao.urls')),
    path('relatorios/',include('relatorios.urls')),
    path('cadastros/', include('cadastros.urls')),
    path('login/', include('login.urls')),
    path('home/', include('core.urls')),
    path('', include('home.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salao/cadastros/cliente/models.py
from django.db import models

from core.models import Base
# Create your models here.

#2.1.1 - Eu como recepcionista, quero cadastrar :
#clientes - nome, telefone, email, data de nascimento, cpf
#serviços - nome, descrição, preço
#profissionais - nome, telefone, email, especialidade


class Cliente(Base):
    nome = models.CharField(
        max_length=100, 
        verbose_name='Nome'
    )
    telefone = models.CharField(
        max_length=20, 
        verbose_name='Telefone'
        )
    email = models.EmailField(
        max_length=100, 
        verbose_name='Email'
        )
    cpf = models.CharField(
        max_length=11, 
        verbose_name='CPF', 
        unique=True
        )
    foto = models.ImageField(
        upload_to='clientes/', 
        blank=True, 
        null=True
    )
    
    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        db_table = 'cliente_cliente'
    
    def __str__(self):
        return f'{self.nome} - {self.cpf} - {self.data_nascimento} - {self.foto}'

salao/cadastros/funcionarios/models.py
from django.db import models

from core.models import Base

from cadastros.servicos.models import *


class Profissional(Base):
    nome = models.CharField(
        max_length=100, 
        verbose_name='Nome'
        )
    telefone = models.CharField(
        max_length=20, 
        verbose_name='Telefone'
        )
    email = models.EmailField(
        max_length=100, 
        verbose_name='Email'
        )
    cpf = models.CharField(
        max_length=11, 
        verbose_name='CPF', 
        unique=True,
        blank=True
        )
    data_contratacao = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Data de Contratação'
        )
    
    

    class Meta:
        verbose_name = 'Profissional'
        verbose_name_plural = 'Profissionais'
        db_table ='cliente_profissional'

    def __str__(self):
        return f'{self.nome}'

salao/cadastros/servicos/models.py
from django.db import models

from core.models import Base


class Servico(Base):
    nome = models.CharField(
        max_length=100, 
        verbose_name='Serviço'
        )
    descricao = models.TextField(
        verbose_name='Descrição'
        )
    preco = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        verbose_name='Valor'
        )

    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'
        db_table = 'cliente_servico'
    
    def __str__(self):
        return f'{self.nome}'

salao/cadastros/cliente/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Cliente
from relatorios.clientes.views import get_relatorio_clientes

# Create your views here.
def cadastro_usuario(request):
    if request.method == "GET":
        return render (request, "cadastros/clientes/cadastrar_login.html")
    else:
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        telefone = request.POST.get('telefone')
        cpf = request.POST.get('cpf')

        user = Cliente(
            nome=nome,
            email=email,
            telefone=telefone,
            cpf=cpf)
        
        user.save()

        return redirect('/cadastros/cliente/criar_cliente/')

def criar_cliente(request):
    # Inicia a consulta de clientes
    clientes = Cliente.objects.all()

    # Captura filtros do GET
    nome_filtrar = request.GET.get('nome_filtrar')
    email_filtrar = request.GET.get('email_filtrar')
    cpf_filtrar = request.GET.get('cpf_filtrar')

    # Aplica filtros
    if nome_filtrar:
        clientes = clientes.filter(nome__icontains=nome_filtrar)
    if email_filtrar:
        clientes = clientes.filter(email__icontains=email_filtrar)
    if cpf_filtrar:
        clientes = clientes.filter(cpf__icontains=cpf_filtrar)


    # Prepara o contexto com os dados filtrados e a quantidade de agendamentos
    consulta_cliente = get_relatorio_clientes(request)
    if request.method == "GET":
        contexto = {
            'clientes': consulta_cliente['clientes'],
            'qntd_clientes': consulta_cliente['qntd_clientes'],
            'pagina': consulta_cliente['pagina'],
            'limit': consulta_cliente['limit'],
        }
        return render(request, "cadastros/clientes/criar_cliente.html", contexto)

salao/cadastros/funcionarios/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Profissional
from core.utils.helpers import Helpers


def criar_funcionario(request):
    
    if request.method=='GET':
        return render(request, 'cadastro/funcionarios/cadastrar_funcionario.html')
    else:
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        telefone = request.POST.get('telefone')
        cpf = request.POST.get('cpf')

        user = Profissional(
            nome=nome,
            email=email,
            telefone=telefone,
            cpf=cpf
            )
        
        user.save()

        return redirect('/servicos/agendamento/')
    

def listar_funcionario(request):
    # Inicia a consulta de profissionais
    profissionais = Profissional.objects.all()
    consulta_func = Helpers.get_funcionarios(request)

    # Captura filtros do GET
    nome_filtrar = request.GET.get('nome_filtrar')
    email_filtrar = request.GET.get('email_filtrar')
    cpf_filtrar = request.GET.get('cpf_filtrar')

    # Aplica filtros
    if nome_filtrar:
        profissionais = profissionais.filter(nome__icontains=nome_filtrar)
    if email_filtrar:
        profissionais = profissionais.filter(email__icontains=email_filtrar)
    if cpf_filtrar:
        profissionais = profissionais.filter(cpf__icontains=cpf_filtrar)


    if request.method == "GET":
        contexto = {
            'profissionais': consulta_func['profissionais'],
            'qntd_profissionais': consulta_func['qntd_profissionais'],

            'pagina': consulta_func['pagina'],
            'limit': consulta_func['limit'],
        }

        return render(request, 'cadastro/funcionarios/listar_funcionario.html', contexto)  # Ajuste para o template correto


def editar_funcionario(request, id):
    profissional = Profissional.objects.get(id=id)  # Busca o profissional pelo ID

    # Se for um GET, renderiza o formulário de edição
    if request.method == 'GET':
        return render(request, "cadastro/funcionarios/editar_funcionario.html", {'profissional': profissional})
    else:
        # Se for um POST, atualiza os dados do profissional
        profissional.nome = request.POST.get('nome')
        profissional.email = request.POST.get('email')
        profissional.telefone = request.POST.get('telefone')
        profissional.cpf = request.POST.get('cpf')
        
        profissional.save()  # Salva as alterações

        # Redireciona para a lista de profissionais
        return redirect('/cadastros/funcionarios/listar_funcionarios/')
    
def deletar_funcionario(request, id):
    profissional=Profissional.objects.get(id=id)
    profissional.delete()
    return redirect(
        '/cadastros/funcionarios/listar_funcionarios/'
        )

salao/cadastros/servicos/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404

from cadastros.servicos.models import Servico

def cadastrar_servico(request):
    pagina = int(request.GET.get('pagina', 1))
    limit = 10  # define o limite por página

    servicos = Servico.objects.all()
    qtd_serv = servicos.count()

    offset = (pagina - 1) * limit
    servicos = servicos.order_by('nome')[offset:offset + limit]

    context = {
        'servicos': servicos,
        'qtd_serv': qtd_serv,
        'limit': limit,
        'pagina': pagina,
    }

    if request.method == 'GET':
        return render(request, 'cadastros/servicos/cadastro_Servico.html', context)
    else:
        nome_servico = request.POST.get('nome_servico')
        descricao = request.POST.get('descricao')
        preco = request.POST.get('preco')

        serv = Servico(
            nome=nome_servico,
            descricao=descricao,
            preco=preco,
        )
        serv.save()


def criar_servico(request):
    if request.method == 'GET':
        return render(request, 'cadastros/servicos/criar_servico.html')
    else:
        nome_servico = request.POST.get('nome_servico')
        descricao = request.POST.get('descricao')
        preco = request.POST.get('preco')

        serv = Servico(
            nome=nome_servico,
            descricao=descricao,
            preco=preco,
        )
        serv.save()
        return redirect('/cadastros/servicos/cadastrar_servico/')
    

def editar_servico(request,id):
    servico = get_object_or_404(Servico, id=id)

    if request.method == 'GET':
        return render(request, 'cadastros/servicos/editar_servico.html', {'servico':servico})
    else:
        descricao = request.POST.get('descricao')
        preco = request.POST.get('preco')

        servico.descricao=descricao
        servico.preco=preco
        servico.save()
        return redirect('/cadastros/servicos/cadastrar_servico/')

    
def deletar_servico(request,id):
    servico=Servico.objects.get(id=id)
    servico.delete()
    return redirect(
        '/cadastros/servicos/cadastrar_servico/'
        )

salao/login/clientes/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


# Create your views here.
def login_user(request):
    
    if request.method == "GET":
        return render (request, 'login.html')
    else:
        username=request.POST.get('username')
        senha=request.POST.get('senha')

        user = authenticate(username=username, password=senha)

        if user:
            login(request, user)

            return HttpResponse('Deu bom')
        else: 
            return HttpResponse('Usuario ou senha invalidos')

salao/relatorios/clientes/views.py
from math import ceil

from django.shortcuts import render, redirect

from servicos.agendamento.models import Agendamento
from cadastros.cliente.models import Cliente


def relatorio_clientes(request):
    limit = 25
    pagina = int(request.GET.get('pagina', 1))

    clientes = Cliente.objects.all()
    qntd_clientes = clientes.count()
    nome_filtrar=request.GET.get('nome_filtrar')
    email_filtrar=request.GET.get('email_filtrar')
    tipo_usuario_filtrar= request.GET.get('tipo_usuario_filtrar')

    if nome_filtrar:
        clientes = clientes.filter(nome__contains=nome_filtrar)
    
    if email_filtrar:
        clientes = clientes.filter(email__contains=email_filtrar)
    
    if tipo_usuario_filtrar:
        clientes = clientes.filter(tipo_usuario__iexact=tipo_usuario_filtrar.lower())

    total_paginas = ceil(qntd_clientes / limit)
    paginas = list(range(1, total_paginas + 1))

    offset = (pagina - 1) * limit
    clientes = clientes.order_by('nome')[offset:offset + limit]

    contexto = {
        'clientes': clientes,
        'qntd_clientes': qntd_clientes,
        'pagina': pagina,
        'limit': limit,
        'total_paginas': total_paginas,
        'paginas': paginas,
    }

    return render(
        request,
        "clientes/relatorio_clientes.html",
        contexto
        )


def ver_cliente(request,id):
    cliente=Cliente.objects.get(id=id)
    return  render(
        request,
        "clientes/ver_clientes.html",
        {'cliente': cliente}
        )


def ver_agendamento(request, id):
    agendamento=Agendamento.objects.get(id=id)
    return  render(
        request,
        "agendamentos/ver_agendamento.html",
        {'agendamento': agendamento}
    )


def deletar_cliente(request,id):
    cliente=Cliente.objects.get(id=id)
    cliente.delete()
    return redirect(
        '/cadastros/cliente/criar_cliente/'
        )

def deletar_agendamento(request, id):
    agendamento = Agendamento.objects.get(id=id)
    agendamento.delete()
    return redirect(
        '/relatorios/agendamentos/'
        )


def get_relatorio_clientes(request):
    limit = 10
    pagina = int(request.GET.get('pagina', 1))
    letra = request.GET.get("letra")  

    clientes = Cliente.objects.all()
    nome_filtrar=request.GET.get('nome_filtrar')
    email_filtrar=request.GET.get('email_filtrar')
    cpf_filtrar = request.GET.get('cpf_filtrar')
    phone_filtrar = request.GET.get('phone_filtrar')

    clientes = Cliente.objects.all()

    if nome_filtrar:
        clientes = clientes.filter(nome__contains=nome_filtrar)
    
    if email_filtrar:
        clientes = clientes.filter(email__contains=email_filtrar)

    if cpf_filtrar:
        clientes = clientes.filter(cpf__contains=cpf_filtrar)
    
    if phone_filtrar:
        clientes = clientes.filter(telefone__contains=phone_filtrar)
    
    if letra:
        clientes = Cliente.objects.filter(nome__istartswith=letra)
    

    qntd_clientes = clientes.count()

    total_paginas = ceil(qntd_clientes / limit)
    paginas = list(range(1, total_paginas + 1))

    offset = (pagina - 1) * limit
    clientes = clientes.order_by('nome')[offset:offset + limit]

    contexto = {
        'clientes': clientes,
        'qntd_clientes': qntd_clientes,
        'pagina': pagina,
        'limit': limit,
        'total_paginas': total_paginas,
        'paginas': paginas,
        'letra': letra
    }

    return (contexto)

salao/cadastros/cliente/templates/cadastros/clientes/cadastrar.html
{%load static%}
<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro Cliente</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0"/>
    <link rel="stylesheet" href="{% static 'cliente_static/css/cadastro_Style.css' %}">

    <title>Cadastro Sign in</title>
</head>
<body class="body">
    <div class="div-cadastro">
        <form class="form-cadastro" action="{% url 'cadastros:cliente'%}" method="POST">{%csrf_token%}
            <label class="form-label">Cadastro</label>
            <br>
            
            <div class="form-div-primary">
                <input class="form-input" type="text" placeholder="Nome" name="first_name">
                <input class="form-input" type="text" placeholder="Sobrenome" name="last_name">
            </div>

            <div class="form-div-secondary">
                <input class="form-input" type="text" placeholder="Usuario" name="username">
                <input class="form-input" type="email" placeholder="email" name= 'email' id="">
            </div>

            <div class="form-div-third">
                <input class="form-input" type="number" placeholder="telefone" name= 'telefone' id="">
                <input class="form-input type-data" type="date" placeholder="data de nascimento" name= 'bornday' id="">
            </div>

            <div class="form-div-fourth">
                <input class="form-input type-password" type="password" placeholder="senha" name="senha" id="">
                <input class="form-input type-password" type="password" placeholder="repita sua senha" name="senha" id="">
            </div>

            <br>
            <input class="form-btn" type="submit" value="cadastrar" id="">
        </form>

    </div>
</body>
</html>

salao/cadastros/cliente/templates/cadastros/clientes/cadastrar_login.html
{%load static%}
<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro Cliente</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0"/>
    <link rel="stylesheet" href="{% static 'cliente_static/css/criacao_Style.css' %}">
</head>
<body class="body">
    {% include 'core/navbar.html' %}
    {% include 'core/sidebar.html'%}
        <form class="form-cadastro" action="" method="POST">{% csrf_token %}
            <h4><label class="name-form">Cadastre seu Cliente</label></h4>
            <div class="form-div-primary">
                <label for="nome">Nome:</label>
                <input 
                class="form-input" 
                type="text" 
                name="nome" 
                placeholder="Digite seu nome"
                >
    
                <label for="email">Email:</label>
                <input 
                class="form-input" 
                type="email" 
                name="email" 
                placeholder="Digite seu e-mail"
                >
               
                <label for="telefone">Telefone:</label>
                <input 
                class="form-input" 
                type="text" 
                name="telefone" 
                placeholder="Digite seu telefone"
                maxlength="15"
                >
               
                <label for="tipo_usuario">Cpf</label>
                <input 
                class="form-input" 
                type="text" 
                name="cpf" 
                placeholder="Digite seu cpf"
                maxlength="14"
                >
                <br>
            </div>
            <input class="form-btn" type="submit" value="Salvar" class ="btn btn-success">
        </form>      
        </div>
</body>
</html>

salao/cadastros/cliente/templates/cadastros/clientes/criar_cliente.html
{%load static%}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Clientes</title>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'servico_static/css/servico_style.css' %}">
</head>
<body>
  {% include 'core/navbar.html' %}
  {% include 'core/sidebar.html' %}
  
  <div class="container">
    <div class="form-div-secondary">
      <form class="form-cadastro" action="" method="GET">
        <h2>Consultar Cliente</h2>
        {% csrf_token %}
        <div class="filtros">

        <label for="nome">Nome</label>
        <input type="text" 
          id="nome" 
          name="nome_filtrar" 
          class="form-input"
        >
        <label for="email">Email</label>
        <input type="text"
          id="email" 
          name="email_filtrar" 
          class="form-input"
        >
        <label for="">CPF</label>
        <input type="text" 
          id="cpf" 
          name="cpf_filtrar" 
          class="form-input"
        >
        <label for="">Telefone</label>
        <input type="number"
        id="phone"
        name="phone_filtrar"
        class="form-input"
        >

        <input type="submit" 
          value="Filtrar" 
          class="form-btn"
        >
        <a class="form-btn" 
          href="/cadastros/cliente/cliente">
          Cadastrar cliente</a>
          </div>
      </form>
      <div class="filtro-alfabeto">
        {% for l in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}
        <a href="?letra={{ l }}" 
        class="">
        {{ l }}</a>
        {% endfor %}
        <a href="?">Todos</a>
      </div>
    </div>

    <!-- Lista de Clientes -->
    <div class="card services-card">
      <h3>Clientes Cadastrados</h3>

      {% for c in clientes %}
      <div class="service-item">
        <div class="service-icon">💇</div>
        <div class="service-content">
          <h3>Cliente : {{ c.nome }}</h3>
          <h3>Telefone: ({{ c.telefone }}) - CPF: {{ c.cpf }} </h3>
          <h3>Email: {{ c.email }} - Ativo: {{ c.ativo|yesno:"Sim,Não" }}</h3>
        </div>
        <div class="service-actions">
          <a href="{% url 'relatorios:ver_cliente' c.id %}"><button>✏️</button></a>
          <a href="/relatorios/deletar_cliente/{{c.id}}"><button>🗑️</button></a>
        </div>
      </div>
      {% empty %}
        <p>Nenhum serviço cadastrado.</p>
      {% endfor %}
    </div>
  </div>
</body>
</html>

salao/cadastros/cliente/templates/cadastros/clientes/perfil.html
{%load static%}
<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro Cliente</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0"/>
    <link rel="stylesheet" href="{% static 'cliente_static/css/bup.css' %}">
</head>
<body class="body">
    {% include 'core/navbar.html' %}
    {% include 'core/sidebar.html'%}
    <div class="div-Form">
        <div>
        <form class="form-cadastro" action="" method="POST">{% csrf_token %}
            <h4><label class="name-form">Cadastre seu Cliente</label></h4>
            <div class="form-div-primary">
                <label for="nome">Nome:</label>
                <input class="form-input" type="text" name="nome" placeholder="Digite seu nome">
    
                <label for="email">Email:</label>
                <input class="form-input" type="email" name="email" placeholder="Digite seu e-mail">
               
                <label for="telefone">Telefone:</label>
                <input class="form-input" type="text" name="telefone" placeholder="Digite seu telefone">
               
                <label for="tipo_usuario">Cpf</label>
                <input class="form-input" type="text" name="cpf" placeholder="Digite seu cpf">
                <br>
            </div>
            <input class="form-btn" type="submit" value="Salvar" class ="btn btn-success">
        </form>      
        <div class="form-div-secondary">
            <form class="form-cadastro" action="" method="GET">
                <h4><label class="name-form">Consultar Cliente</label></h4>
                {% csrf_token %}
                <label for="nome">Nome</label>
                <input type="text" id="nome" name="nome_filtrar" class="form-input">
                <label for="email">Email</label>
                <input type="text" id="email" name="email_filtrar" class="form-input">
                <input type="submit" value="Filtrar" class="form-btn">
            </form>
        </div>
        </div>
        
        <div class="container">
            
        <div class="form-cadastro div-log">
            {% if clientes %}
            <ul>
            {% for c in clientes %}
                <div class="div-log registro">
                    <li>
                        <strong>{{ c.nome }}</strong> ({{ c.telefone }})
                        <div class="info">
                            CPF: {{ c.cpf }} –
                            Email: {{ c.email }} –
                            Ativo: {{ c.ativo|yesno:"Sim,Não" }}
                        </div>

                        <a href="{% url 'relatorios:ver_cliente' c.id %}" class="btn">Editar</a>
                        <a href="/relatorios/deletar_cliente/{{c.id}}" class="btn">❌ Excluir</a>
                    </li>
                </div>
            {% endfor %}
            </ul>
            {% else %}
                <p>Nenhum cliente encontrado.</p>
            {% endif %}
        </div>
        
        <form class="form-cadastro">
            <span class="qtd_age">Total de Clientes: {{ qtd_clientes }}</span>
            <a class="form-btn" href="?pagina={{ pagina|add:-1 }}">Anterior</a>
            <a class="form-btn" href="?pagina={{ pagina|add:1 }}">Próxima</a>
        </form> 
        </div>
        <div class="filtro-alfabeto">
                {% for l in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}
                    <a href="?letra={{ l }}" class="">{{ l }}</a>
                {% endfor %}
                <a href="?">Todos</a>
        </div>
        </div>
</body>
</html>